export const moviesData = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    category: 'Drama',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    poster: './img/Cadena.jpg',
  },
  {
    id: 2,
    title: 'Inception',
    category: 'Action',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    poster: './img/inception.jpg',
  },
  {
    id: 3,
    title: 'The Godfather',
    category: 'Crime',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    poster: './img/thegodfather.jpg',
  },
  {
    id: 4,
    title: 'Forrest Gump',
    category: 'Drama',
    description: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.',
    poster: './img/forestgump.jpg',
  },
  {
    id: 5,
    title: 'The Dark Knight',
    category: 'Action',
    description: 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
    poster: './img/batman.jpg',
  },
  {
    id: 6,
    title: 'Schindler\'s List',
    category: 'Biography',
    description: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    poster: './img/schindlerlist.jpg',
  },
  {
    id: 7,
    title: 'Pulp Fiction',
    category: 'Crime',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    poster: './img/pulpfiction.jpg',
  },
  {
    id: 8,
    title: 'The Matrix',
    category: 'Action',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    poster: './img/matrix.jpg',
  },
  {
    id: 9,
    title: 'Titanic',
    category: 'Drama',
    description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    poster: './img/titanic.jpg',
  },
  {
    id: 10,
    title: 'The Silence of the Lambs',
    category: 'Action',
    description: 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    poster: './img/thesilenceoflambs.jpg',
  },
  {
    id: 11,
    title: 'The Social Network',
    category: 'Biography',
    description: 'A drama about the founding of the social networking site Facebook and the resulting lawsuits.',
    poster: './img/thesocialnwtwork.jpg',
  },
  {
    id: 12,
    title: 'A Beautiful Mind',
    category: 'Biography',
    description: 'A brilliant mathematician struggles with schizophrenia while making groundbreaking contributions to mathematics.',
    poster: './img/ABeautifulMind.jpg',
  }
];